.\" Manpage for paprass.
.\" Contact zlatan.todoric@gmail.com to correct errors or typos.
.TH paprass 1 "09 April 2012" "1.0" "paprass man page"
.SH NAME
paprass \- manager of electronic documents
.SH DESCRIPTION
Pap'rass is an application that will interface with your
scanner to save documents and index, annotate, classify,
and search them.
.SH AUTHOR
Alain Delgrange
